In [1]:
import pandas as pd
import numpy as np
import matplotlib as mlt
import csv

In [4]:
df_recipes = pd.read_csv('C:/Users/user/Downloads/archive (3)/recipes.csv')

In [5]:
df_recipes.columns

Index(['RecipeId', 'Name', 'AuthorId', 'AuthorName', 'CookTime', 'PrepTime',
       'TotalTime', 'DatePublished', 'Description', 'Images', 'RecipeCategory',
       'Keywords', 'RecipeIngredientQuantities', 'RecipeIngredientParts',
       'AggregatedRating', 'ReviewCount', 'Calories', 'FatContent',
       'SaturatedFatContent', 'CholesterolContent', 'SodiumContent',
       'CarbohydrateContent', 'FiberContent', 'SugarContent', 'ProteinContent',
       'RecipeServings', 'RecipeYield', 'RecipeInstructions'],
      dtype='object')

In [6]:
df_recipes[['Name','RecipeIngredientParts']]

,Name,RecipeIngredientParts
0,Low-Fat Berry Blue Frozen Dessert,"c(""blueberries"", ""granulated sugar"", ""vanilla ..."
1,Biryani,"c(""saffron"", ""milk"", ""hot green chili peppers""..."
2,Best Lemonade,"c(""sugar"", ""lemons, rind of"", ""lemon, zest of""..."
3,Carina's Tofu-Vegetable Kebabs,"c(""extra firm tofu"", ""eggplant"", ""zucchini"", ""..."
4,Cabbage Soup,"c(""plain tomato juice"", ""cabbage"", ""onion"", ""c..."
...,...,...
522512,Meg's Fresh Ginger Gingerbread,"c(""fresh ginger"", ""unsalted butter"", ""dark bro..."
522513,Roast Prime Rib au Poivre with Mixed Peppercorns,"c(""Dijon mustard"", ""garlic"", ""peppercorns"", ""s..."
522514,Kirshwasser Ice Cream,"c(""half-and-half"", ""heavy cream"", ""brandy"", ""s..."
522515,Quick & Easy Asian Cucumber Salmon Rolls,"c(""wasabi paste"", ""dill"", ""English cucumber"", ..."
522516,Spicy Baked Scotch Eggs,"c(""hard-boiled eggs"", ""breakfast sausage"", ""pa..."

In [8]:
print(df_recipes.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 522517 entries, 0 to 522516
Data columns (total 28 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   RecipeId                    522517 non-null  int64
 1   Name                        522517 non-null  object
 2   AuthorId                    522517 non-null  int64
 3   AuthorName                  522517 non-null  object
 4   CookTime                    439972 non-null  object
 5   PrepTime                    522517 non-null  object
 6   TotalTime                   522517 non-null  object
 7   DatePublished               522517 non-null  object
 8   Description                 522512 non-null  object
 9   Images                      522516 non-null  object
 10  RecipeCategory              521766 non-null  object
 11  Keywords                    505280 non-null  object
 12  RecipeIngredientQuantities  522514 non-null  object
 13  RecipeIngredientParts       522517 non-null  object
 14  AggregatedRating            269294 non-null  float64
 15  ReviewCount                 275028 non-null  float64
 16  Calories                    522517 non-null  float64
 17  FatContent                  522517 non-null  float64
 18  SaturatedFatContent         522517 non-null  float64
 19  CholesterolContent          522517 non-null  float64
 20  SodiumContent               522517 non-null  float64
 21  CarbohydrateContent         522517 non-null  float64
 22  FiberContent                522517 non-null  float64
 23  SugarContent                522517 non-null  float64
 24  ProteinContent              522517 non-null  float64
 25  RecipeServings              339606 non-null  float64
 26  RecipeYield                 174446 non-null  object
 27  RecipeInstructions          522517 non-null  object
dtypes: float64(12), int64(2), object(14)
memory usage: 111.6+ MB
None

In [9]:
df_vegan = pd.read_csv('C:/Users/user/Downloads/Datasets-D/vegan.csv')

In [10]:
print(df_vegan.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1522 entries, 0 to 1521
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Diet_type        1522 non-null   object
 1   Recipe_name      1522 non-null   object
 2   Cuisine_type     1522 non-null   object
 3   Protein(g)       1522 non-null   float64
 4   Carbs(g)         1522 non-null   float64
 5   Fat(g)           1522 non-null   float64
 6   Extraction_day   1522 non-null   object
 7   Extraction_time  1522 non-null   object
dtypes: float64(3), object(5)
memory usage: 95.3+ KB
None

In [15]:
df_vegan.head(10)

,Diet_type,Recipe_name,Cuisine_type,Protein(g),Carbs(g),Fat(g),Extraction_day,Extraction_time
0,vegan,Spiked Vegan Eggnog,american,46.36,84.52,42.61,2022-10-16,20:02:29
1,vegan,Vegan Cucumber Tea Sandwiches,american,41.73,143.91,73.88,2022-10-16,20:02:29
2,vegan,Vegan Broccoli Soup Recipe,american,103.83,82.54,139.30,2022-10-16,20:02:29
3,vegan,Baked Vegan Mac and Cheese Recipe,american,140.19,524.38,221.29,2022-10-16,20:02:29
4,vegan,Vegan Nachos,american,73.05,266.38,166.64,2022-10-16,20:02:29
5,vegan,The Best Vegan Breakfast Sandwich,american,143.13,208.42,189.86,2022-10-16,20:02:29
6,vegan,{Vegan} Peanut Butter & Honey Muffins recipes,american,29.53,168.46,59.83,2022-10-16,20:02:29
7,vegan,Vegan Pots de Crème,american,45.25,106.45,98.01,2022-10-16,20:02:29
8,vegan,Vegan tiffin,american,60.38,272.18,287.22,2022-10-16,20:02:29
9,vegan,Vegan Stovetop Lasagna,american,124.77,512.21,147.15,2022-10-16,20:02:29

In [11]:
df_meal_plans = pd.read_csv('C:/Users/user/Downloads/Datasets-D/healthy_meal_plans.csv')

In [12]:
print(df_meal_plans.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   meal_name        500 non-null    object
 1   num_ingredients  500 non-null    float64
 2   calories         500 non-null    float64
 3   prep_time        500 non-null    float64
 4   protein          500 non-null    float64
 5   fat              500 non-null    float64
 6   carbs            500 non-null    float64
 7   vegan            500 non-null    int64
 8   vegetarian       500 non-null    int64
 9   keto             500 non-null    int64
 10  paleo            500 non-null    int64
 11  gluten_free      500 non-null    int64
 12  mediterranean    500 non-null    int64
 13  is_healthy       500 non-null    int64
dtypes: float64(6), int64(7), object(1)
memory usage: 54.8+ KB
None

In [14]:
df_meal_plans.head(10)

,meal_name,num_ingredients,calories,prep_time,protein,fat,carbs,vegan,vegetarian,keto,paleo,gluten_free,mediterranean,is_healthy
0,Gluten-Free Pasta,0.272727,0.490909,0.84,0.783679,0.597907,0.444572,0,0,0,0,1,0,1
1,Grilled Salmon,0.909091,0.158182,0.70,0.143588,0.652082,0.050609,0,0,1,1,1,1,0
2,Lentil Soup,0.454545,0.700000,0.40,0.620637,0.612748,0.000688,0,1,0,0,0,0,0
3,Chickpea Stew,0.909091,0.105455,0.82,0.046893,0.975761,0.229026,1,1,0,0,0,0,0
4,Turkey Lettuce Wraps,0.181818,0.441818,0.04,0.864340,0.681575,0.449293,0,0,1,1,1,1,0
5,Cauliflower Rice Bowl,0.272727,0.572727,0.26,0.812533,0.304936,0.092351,1,1,0,1,1,0,1
6,Almond Flour Pancakes,1.000000,0.665455,0.12,0.613114,0.834846,0.168926,0,1,1,1,1,0,0
7,Chickpea Stew,0.272727,0.703636,0.02,0.427325,0.208021,0.567861,1,1,0,0,0,0,1
8,Cauliflower Rice Bowl,0.818182,0.292727,0.18,0.899406,0.598960,0.926165,1,1,0,1,1,0,0
9,Vegan Curry,0.545455,0.456364,0.78,0.848855,0.748756,0.539526,1,1,0,0,0,0,0